### ISSUE TITLE
Sprockets::FileOutsidePaths Error after update.

### ISSUE THREAD

**Issue by zw963** [hmdne/roda-sprockets#13]
Following is error info when run test.

Sprockets::FileOutsidePaths: /gems/opal-1.3.2/opal/opal.rb is no longer under a load path: /assets/css, /assets/js, /vendor/assets/materialize-src, /opal-1.3.2/opal, /opal-1.3.2/stdlib, /opal-1.3.2/lib, /ast-2.4.2/lib, /ast-2.4.2/lib, /parser-3.0.3.1/lib, /snabberb-1.5.4/opal, /opal-browser-0.3.1/opal, /paggio-0.3.0/lib
    /sprockets-4.0.2/lib/sprockets/loader.rb:156:in `load_from_unloaded'
    /sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
    /sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
    /sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
    /sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
    ...

Test is working before.

**Comment by zw963** [comment]
it should be a opal-sporkets issue.
